[workspace]
resolver = "3"
members = [ "app","geerpc"]

[workspace.dependencies]
snafu = "0.8.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
