[package]
name = "geerpc"
version = "0.1.0"
edition = "2024"

[features]
internal-testing = []

[dependencies]
snafu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]